// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDryLh_K6dXw-Szab7HDUf6czJJ5aXqMA',
    appId: '1:572492809728:web:93f76d33debbcf3fc6fae5',
    messagingSenderId: '572492809728',
    projectId: 'auth-fb76d',
    authDomain: 'auth-fb76d.firebaseapp.com',
    storageBucket: 'auth-fb76d.appspot.com',
    measurementId: 'G-42VWVJ13ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5nUG3YfAxZAt9uedA7Syq0fPMYmkhUO4',
    appId: '1:572492809728:android:163fb561708827f9c6fae5',
    messagingSenderId: '572492809728',
    projectId: 'auth-fb76d',
    storageBucket: 'auth-fb76d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXeaZ_BmixzcoLu8oHZ85bRg8O0fYyR8k',
    appId: '1:572492809728:ios:1b1e175ebe46dd2cc6fae5',
    messagingSenderId: '572492809728',
    projectId: 'auth-fb76d',
    storageBucket: 'auth-fb76d.appspot.com',
    iosClientId: '572492809728-v1f7adhcsvcqqnp1n49gvv2ikjmskivs.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );
}
